name: Run test-cases
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
  issues: write
  
jobs:
  run_test_cases:
    runs-on: ubuntu-latest

    steps:
    - name: Keploy Report
      uses: keploy/testgpt@main
      with:
        working-directory: ./
        delay: 10
        command: go run main.go
        keploy-path: ./