name: Keploy TestGPT Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: echo "WORKDIR=${{ github.workspace }}/${{ inputs.working-directory }}" >> $GITHUB_ENV

      - name: Detect languages
        id: language-detection
        shell: bash
        run: |
          declare -A extensions=(
            ["go"]="go"
            ["js"]="javascript"
            ["ts"]="javascript" 
            ["py"]="python"
            ["java"]="java"
          )

          LANGUAGES=""
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            ext="${file##*.}"
            if [[ -n "${extensions[$ext]}" ]]; then
              LANGUAGES+="${extensions[$ext]} "
            fi
          done

          UNIQUE_LANGS=$(echo "$LANGUAGES" | tr ' ' '\n' | sort -u | tr '\n' ' ')
          echo "languages=$UNIQUE_LANGS" >> $GITHUB_ENV

      - name: Install analysis tools
        shell: bash
        run: |
          for lang in ${{ env.languages }}; do
            case "$lang" in
              go)
                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
                go install github.com/securego/gosec/v2/cmd/gosec@latest
                ;;
              javascript)
                npm install -g eslint
                ;;
              python)
                pip install flake8 bandit
                ;;
            esac
          done

      - name: Run Code Analysis
        shell: bash
        run: |
          mkdir -p analysis-reports
          cd $WORKDIR
          
          for lang in ${{ env.languages }}; do
            case "$lang" in
              go)
                golangci-lint run --out-format=github-actions ./... > analysis-reports/go-lint.txt || true
                gosec ./... > analysis-reports/go-security.txt || true
                ;;
              javascript)
                eslint . --format junit -o analysis-reports/js-lint.xml || true
                ;;
              python)
                which flake8 || pip install flake8
                which bandit || pip install bandit
                
                flake8 . --output-file=analysis-reports/py-lint.txt || true
                bandit -r . -f txt -o analysis-reports/py-security.txt || true
                ;;
            esac
          done

      - name: Combine Analysis Reports
        shell: bash
        run: |
          mkdir -p analysis-reports
          temp_file=$(mktemp) # Temporary file to avoid 'input file is output file' issue

          echo "## 📊 Combined TestGPT Analysis Report" > "$temp_file"

          for report in analysis-reports/*; do
            if [ -f "$report" ]; then
              echo "### $(basename "$report")" >> "$temp_file"
              cat "$report" >> "$temp_file"
              echo -e "\n---\n" >> "$temp_file"
            fi
          done

          mv "$temp_file" analysis-reports/final-report.txt

      - name: Set KEPLOY_REPORT Environment Variable
        shell: bash
        run: |
          if [[ -f "analysis-reports/final-report.txt" ]]; then
            KEPLOY_REPORT=$(cat analysis-reports/final-report.txt)
          else
            KEPLOY_REPORT="No test results available."
          fi
          echo "KEPLOY_REPORT<<EOF" >> $GITHUB_ENV
          echo "$KEPLOY_REPORT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on PR with Keploy Report
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reportPath = 'analysis-reports/final-report.txt';
            let reportContent = 'No analysis report available';

            if (fs.existsSync(reportPath)) {
              reportContent = fs.readFileSync(reportPath, 'utf8');
            }

            const summary = `## 📊 TestGPT Analysis Report\n\n${process.env.KEPLOY_REPORT}\n\n${reportContent}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
