name: Generate PR Comments PDF

on:
  workflow_run:
    workflows: ["Lint Workflow", "Security Scan with Trivy", "Run test-cases"]
    types:
      - completed

jobs:
  start-workflow:
      runs-on: ubuntu-latest
      steps:
        - name: Workflow Initialized
          run: echo "Starting workflow execution"

  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch PR comments
        run: |
          COMMENTS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.workflow_run.pull_requests[0].number }}/comments --jq '.[].body')
          echo "$COMMENTS" > comments.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert comments to PDF
        run: |
          sudo apt-get install -y pandoc
          pandoc comments.txt -o comments.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-comments
          path: comments.pdf

      - name: Post PR comment with PDF link
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "PR comments have been compiled into a [PDF report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
