name: Run test-cases
on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Keploy Report
      uses: keploy/testgpt@main
      with:
        working-directory: /
        delay: 10
        command: python app.py
        keploy-path: ./